environment                = "dev"
resource_group_name        = "rg-lhinfra-dev-weu"
region                     = "weu"
workload                   = "lakehouse"
keyvault_sku               = "standard"
secret_scope_keyvault_name = "keyvault"
